# Generated by Django 4.2 on 2023-04-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=75)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=75)),
                ('prod_count', models.IntegerField()),
                ('prod_price', models.FloatField()),
                ('prod_photo', models.ImageField(upload_to='media')),
                ('prod_des', models.TextField()),
                ('prod_rdate', models.DateTimeField(auto_now_add=True)),
                ('prod_coteg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.category')),
            ],
        ),
    ]
