# Generated by Django 4.2 on 2023-04-29 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_cart'),
    ]

    operations = {
        migrations.AddField(
            model_name='cart',
            name='cart_reg_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    }
